services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - e2e

  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - main
      - dependency
