services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main@sha256:1b2cf66feab7f30b1718c5b65e66bc77abb4fe036036a1e705e22b087498a941
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,volkovlabs-variable-panel,volkovlabs-form-panel,volkovlabs-image-panel,yesoreyeram-infinity-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-table-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - e2e

  timescale:
    image: timescale/timescaledb:latest-pg14@sha256:0f5553d37abbe0f20bfe0a04dab5d1238955b5cda2711aba403090f95b6e51ff
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - main
      - dependency
